(() => {
  const lessons = [
    { id: "basics", title: "型注釈と推論", time: "6分", desc: "値の形を言葉で伝える", body: "TypeScriptはJavaScriptに『この値は何か』を伝えるための仕組みを足します。`string`、`number`、`boolean` は最初の三つの基本型です。多くの場合、初期値から型を推測してくれます。", code: "let station: string = '東京';\nlet stops = 5;        // number と推論される\nlet express = false;   // boolean と推論される", tip: "型は『動くための命令』ではなく、間違いを早く見つけるためのメモです。実行前にチェックされ、最終的にはJavaScriptになります。" },
    { id: "functions", title: "関数の型", time: "7分", desc: "入力と出力を安全にする", body: "関数では、引数と返り値に型を付けられます。何を受け取り、何を返すのかが一目で分かり、使い方を間違えにくくなります。", code: "function minutesToSeconds(minutes: number): number {\n  return minutes * 60;\n}\n\nminutesToSeconds(3); // 180", tip: "返り値の型は省略しても推論されますが、学び始めは書いておくと関数の役割が明確になります。" },
    { id: "objects", title: "オブジェクトと型", time: "8分", desc: "データの設計図を作る", body: "複数の値をひとまとまりにするオブジェクトには、独自の型を作れます。`type`は、データに必要な項目を決める設計図です。", code: "type Station = {\n  name: string;\n  line: string;\n  accessible?: boolean;\n};\n\nconst stop: Station = { name: '新宿', line: '中央線' };", tip: "`?` を付けた項目は任意です。データがある場合とない場合を、型で表現できます。" },
    { id: "unions", title: "ユニオン型と絞り込み", time: "9分", desc: "複数の可能性を扱う", body: "`string | number` のように `|` で複数の型を許可できます。使う前に `typeof` などで型を絞り込めば、安全にそれぞれの機能を呼び出せます。", code: "function formatId(id: string | number): string {\n  if (typeof id === 'number') {\n    return id.toFixed(0);\n  }\n  return id.toUpperCase();\n}", tip: "ユニオン型は『どちらか』を正確に表す道具です。anyで逃げず、条件分岐で安全に扱う癖をつけましょう。" },
    { id: "generics", title: "ジェネリクス", time: "10分", desc: "型を保ったまま再利用する", body: "ジェネリクスは型を変数のように扱います。`T`は呼び出す人が決める型で、値の種類を失わずに再利用できる関数を作れます。", code: "function first<T>(items: T[]): T | undefined {\n  return items[0];\n}\n\nconst name = first(['Aki', 'Ren']); // string | undefined", tip: "WebAssemblyやライブラリ連携でも、データの型を保つことは大切です。ジェネリクスはそのための基礎になります。" },
    { id: "async", title: "非同期処理とNext.jsへ", time: "10分", desc: "外部データを安全に扱う", body: "ネットワークや保存処理は、結果がすぐ返らないことがあります。`async` / `await` と型付けを組み合わせると、Next.jsのデータ取得にも直結します。", code: "type Article = { id: number; title: string };\n\nasync function getArticle(id: number): Promise<Article> {\n  const response = await fetch(`/api/articles/${id}`);\n  return response.json() as Promise<Article>;\n}", tip: "まずはブラウザだけの小さなプログラムで型に慣れ、その後にNext.jsで画面とデータを組み合わせましょう。" }
  ];
  const questions = [
    { kind:"choice", prompt:"`name` が文字列であることを表す正しい書き方は？", choices:["let name = string;","let name: string = 'Aki';","let string: name = 'Aki';"], answer:1, explain:"`変数名: 型 = 値` の順です。型注釈はコロンの後に書きます。" },
    { kind:"choice", prompt:"次の関数の返り値の型は何ですか？\n`function add(a: number, b: number) { return a + b; }`", choices:["string","number","unknown"], answer:1, explain:"引数がnumberで `+` しているので、TypeScriptは返り値をnumberと推論します。" },
    { kind:"code", prompt:"空欄を埋め、`title` が文字列のプロパティである型を完成させてください。", starter:"type Book = {\n  title: ____;\n};", answer:"string", explain:"プロパティの型も `プロパティ名: 型` の形です。" },
    { kind:"choice", prompt:"`string | number` は何を表しますか？", choices:["文字列か数値のどちらか","文字列と数値を連結する","型チェックを無効にする"], answer:0, explain:"`|` はユニオン型です。複数の可能性を明示し、使う前に型を絞り込みます。" },
    { kind:"code", prompt:"配列の先頭要素を返すジェネリック関数の空欄を埋めてください。", starter:"function first<T>(items: T[]): ____ {\n  return items[0];\n}", answer:"T | undefined", explain:"空配列なら値がないのでundefinedも含みます。`T` により要素の型を保てます。" },
    { kind:"choice", prompt:"非同期関数が `Article` を返すときの型として正しいものは？", choices:["Article","Promise<Article>","async<Article>"], answer:1, explain:"async関数は値をPromiseで包んで返します。その中身を `Promise<Article>` と表します。" }
  ];
  const roadmap = [["01","TypeScript 基礎","型注釈、関数、オブジェクト、ユニオン型を学び、小さなプログラムを安全に書く。","いまここ"],["02","ブラウザ API","DOM、localStorage、Fetchを扱い、ユーザーが触れる小さなアプリを作る。","次の一歩"],["03","Next.js","Reactのコンポーネント、ルーティング、データ取得を学び、実用的なWebアプリへ。","研究の土台"],["04","WebAssembly","Rustなどで書いた高速な処理をWebから呼び、型・メモリ・境界を理解する。","発展"]];
  const key = "ts-train-progress-v1";
  const state = Object.assign({ done:[], answers:{}, visited:0 }, JSON.parse(localStorage.getItem(key) || "{}"));
  const app = document.querySelector("#app"); const toast = document.querySelector("#toast");
  const esc = value => String(value).replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[c]);
  const save = () => localStorage.setItem(key, JSON.stringify(state));
  const progress = () => Math.round(state.done.length / lessons.length * 100);
  const showToast = message => { toast.textContent = message; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2500); };
  const setNav = page => document.querySelectorAll("[data-nav]").forEach(n => n.classList.toggle("active", n.dataset.nav === page));
  const home = () => { setNav("home"); app.innerHTML = `<section class="hero"><div class="eyebrow">Offline learning / TypeScript</div><h1>電車の時間を、<br>型が読める時間に。</h1><p class="lead">通信なしで学べる、短くて手を動かすTypeScript教材。基礎からNext.js、そしてWebAssemblyへつながる道のりを作ります。</p><div class="button-row"><a class="btn" href="#learn">レッスンを始める</a><a class="btn secondary" href="#practice">今日の練習</a></div></section><section class="grid home-grid"><article class="card continue-card"><div><span class="kicker">あなたの進捗</span><h2>${state.done.length ? "続きから学ぶ" : "最初の1レッスンから"}</h2><div class="progress-bar"><span style="width:${progress()}%"></span></div><div class="progress-copy">${state.done.length} / ${lessons.length} レッスン完了 (${progress()}%)</div></div><a class="btn" href="#learn/${state.done.length < lessons.length ? lessons.find(x=>!state.done.includes(x.id)).id : lessons[0].id}">${state.done.length ? "次のレッスンへ" : "型注釈を学ぶ"}</a></article><article class="card"><h2>学習の記録</h2><p>小さく進めるほど、型は自分の言葉になります。</p><div class="stats"><div class="stat"><strong>${state.done.length}</strong><span>完了</span></div><div class="stat"><strong>${Object.keys(state.answers).filter(k=>state.answers[k]).length}</strong><span>正解</span></div><div class="stat"><strong>${lessons.reduce((s,l)=>s+(state.done.includes(l.id)?Number(l.time.replace("分","")):0),0)}</strong><span>学習分</span></div></div></article></section><section class="card" style="margin-top:16px"><div class="eyebrow">電車で使うコツ</div><h2>出発前に一度だけ開けばOK</h2><p>このアプリは端末に教材を保存します。画面右上が「オフラインでも利用可能」になったら、通信を切ってもレッスンと練習、進捗保存を使えます。</p></section>`; };
  const learn = () => { setNav("learn"); app.innerHTML = `<div class="section-head"><div><div class="eyebrow">Curriculum</div><h1>TypeScriptを学ぶ</h1></div><span class="progress-copy">${progress()}% 完了</span></div><p class="lead">順番に取り組んでも、気になる項目から始めても大丈夫です。各レッスンは電車の一区間で終えられる量です。</p><div class="lesson-list">${lessons.map((l,i) => `<a class="lesson ${state.done.includes(l.id)?"done":""}" href="#learn/${l.id}"><span class="lesson-num">${state.done.includes(l.id)?"✓":String(i+1).padStart(2,"0")}</span><span><span class="lesson-title">${l.title}</span><span class="lesson-desc">${l.desc}</span></span><span class="lesson-time">${l.time}</span></a>`).join("")}</div>`; };
  const lesson = id => { const l=lessons.find(x=>x.id===id); if(!l) return learn(); setNav("learn"); const index=lessons.indexOf(l); app.innerHTML = `<article class="lesson-page"><a class="back" href="#learn">← レッスン一覧へ</a><div class="eyebrow" style="margin-top:25px">Lesson ${String(index+1).padStart(2,"0")} / ${l.time}</div><h1>${l.title}</h1><p class="lead">${l.desc}</p><p class="explain">${l.body}</p><pre class="code"><code>${esc(l.code)}</code></pre><div class="callout"><strong>覚えておくこと</strong><br>${l.tip}</div><div class="lesson-actions"><a class="btn secondary" href="#practice">理解度を確認</a><button class="btn" id="complete">${state.done.includes(l.id)?"完了済み ✓":"このレッスンを完了"}</button></div></article>`; document.querySelector("#complete").onclick = () => { if(!state.done.includes(l.id)) { state.done.push(l.id); save(); showToast("レッスンを完了として記録しました"); } location.hash = index < lessons.length-1 ? `#learn/${lessons[index+1].id}` : "#home"; }; };
  const practice = () => { setNav("practice"); const active = Number(location.hash.split("/")[1] || 0); const q=questions[active] || questions[0]; const solved=state.answers[active]; app.innerHTML = `<div class="section-head"><div><div class="eyebrow">Practice lab</div><h1>手を動かして確認</h1></div><span class="progress-copy">${Object.keys(state.answers).filter(k=>state.answers[k]).length}/${questions.length} 正解</span></div><div class="practice-layout"><div class="question-tabs">${questions.map((_,i)=>`<a href="#practice/${i}" class="q-tab ${i===active?"active":""} ${state.answers[i]?"correct":""}"><b>${i+1}</b><span>問題 ${i+1}</span></a>`).join("")}</div><article class="card question-card"><div class="eyebrow">問題 ${active+1} / ${questions.length}</div><h2>${q.kind==="code"?"コード穴埋め":"選択クイズ"}</h2><p class="question-prompt">${esc(q.prompt).replace(/\n/g,"<br>")}</p>${q.kind==="choice"?`<div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${esc(c)}</button>`).join("")}</div>`:`<pre class="code"><code>${esc(q.starter)}</code></pre><textarea id="code-answer" class="answer-area" placeholder="空欄に入るコードを書いてください"></textarea>`}<div class="button-row"><button id="check" class="btn">答えを確認</button><a class="btn secondary" href="#practice/${Math.min(active+1,questions.length-1)}">次の問題</a></div><div id="feedback" class="feedback hidden"></div></article></div>`;
    let selected=null; document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{ if(solved)return; document.querySelectorAll("[data-choice]").forEach(x=>x.classList.remove("selected")); b.classList.add("selected"); selected=Number(b.dataset.choice); }); document.querySelector("#check").onclick=()=>{ let correct=false; if(q.kind==="choice") { if(selected===null) return showToast("選択肢を選んでください"); correct=selected===q.answer; document.querySelectorAll("[data-choice]").forEach(b=>{ const n=Number(b.dataset.choice); b.classList.add(n===q.answer?"correct":n===selected?"wrong":""); }); } else { const val=document.querySelector("#code-answer").value.trim().replace(/\s+/g," "); correct=val===q.answer; } if(correct) { state.answers[active]=true; save(); } const feedback=document.querySelector("#feedback"); feedback.className=`feedback ${correct?"good":"bad"}`; feedback.innerHTML=`<strong>${correct?"正解です！":"もう一度考えてみましょう"}</strong><br>${q.explain}`; }; };
  const road = () => { setNav("roadmap"); app.innerHTML = `<div class="section-head"><div><div class="eyebrow">Learning path</div><h1>研究につながる道のり</h1></div></div><p class="lead">型を理解すると、複雑な画面・データ・高速処理の境界を安全に設計できるようになります。</p><section class="roadmap">${roadmap.map((r,i)=>`<article class="roadmap-item ${i===0?"active":""}"><div class="roadmap-dot">${r[0]}</div><div><h3>${r[1]}</h3><p>${r[2]}</p><span class="badge">${r[3]}</span></div></article>`).join("")}</section><article class="card"><h2>WebAssemblyに進む前に</h2><p>TypeScriptで「データの形」「非同期の結果」「関数の入出力」を言語化できるようになると、JavaScriptとWebAssemblyの境界を設計する力につながります。焦らず、まずこの6レッスンを一周しましょう。</p><div class="button-row"><a href="#learn" class="btn">基礎から始める</a></div></article>`; };
  const render = () => { const [page,param] = location.hash.slice(1).split("/"); if(page==="learn" && param) lesson(param); else if(page==="learn") learn(); else if(page==="practice") practice(); else if(page==="roadmap") road(); else home(); window.scrollTo(0,0); };
  const network = () => { const on=navigator.onLine; document.querySelector("#network-dot").classList.toggle("offline",!on); document.querySelector("#network-label").textContent=on ? "オンライン" : "オフラインでも利用可能"; };
  window.addEventListener("hashchange",render); window.addEventListener("online",network); window.addEventListener("offline",network); if("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js").catch(()=>{}); network(); render();
})();
